In [3]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [4]:
%time
my_arr = np.arange(1_000_000)

CPU times: user 7 µs, sys: 1 µs, total: 8 µs
Wall time: 17.2 µs


In [5]:
%time
my_list = list(range(1_000_000))

CPU times: user 3 µs, sys: 1 µs, total: 4 µs
Wall time: 12.2 µs


In [7]:
%time my_arr2 = my_arr * 2

CPU times: user 4.08 ms, sys: 7.37 ms, total: 11.5 ms
Wall time: 10.4 ms


In [8]:
%timeit my_list2 = [x * 2 for x in my_list]


48.4 ms ± 994 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [15]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
#row1: [1.5, -0.1, 3], row2: [0, -3, 6.5]
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [13]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [14]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [18]:
data.dtype #(data type in each matrix element) 

dtype('float64')

In [44]:
#Numpy arrays
data1 = [6, 7.5, 8, 0, 1]
#How python array looks

In [45]:
arr1 = np.array(data1)
arr1
#How ndarray looks

array([6. , 7.5, 8. , 0. , 1. ])

In [50]:
#Matrix
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [52]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
arr2.ndim #number of dimensions of array

2

In [54]:
arr2.shape #dimensions of array eg 2 x 4

(2, 4)

In [55]:
arr1.dtype #data type of array elements

dtype('float64')

In [56]:
arr2.dtype

dtype('int64')

In [58]:
#Create a vector (or 1-d list) of zeros 
np.zeros (10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
#To create a matrix, pass in a tuple for the shape
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [64]:
#To create an blank array. May not return zeroes. This will return uninitialized aray of garbage values
np.empty((2, 3, 2))

array([[[0., 0.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 0.],
        [0., 1.]]])

In [68]:
#Data types for ndarrays
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [69]:
arr1.dtype

dtype('float64')

In [70]:
arr1.dtype

dtype('float64')

In [72]:
#Can convert ("cast") an array from one data type to another using astype
arr = np.array([1, 2, 3, 4, 5])

In [73]:
arr.dtype

dtype('int64')

In [76]:
#Convert elements to float
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [78]:
#If we convert ("cast") integers to floating point, decimal part will be truncated
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [80]:
#Can convert ("cast") an array of strings representing numbers to numbers (ints or floats)
numeric_strings = np.array(["3.2", "-6.2", ".542"])
numeric_strings.dtype


dtype('<U4')

In [81]:
numeric_strings.astype(np.float64)

array([ 3.2  , -6.2  ,  0.542])

In [82]:
#argument for astype can also be another array's type
int_array = np.arange(10) #Creates an array whose elements RANGE from 1 to 10, hence the name
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#See table 4.1 for more NumPy array creation functions

In [26]:
#abc